### ISSUE TITLE
Updating to Contao 4.6 causes an error ...

### ISSUE THREAD

**Issue by Seefahrer** [webrealisierung-ch/onepage-bundle#11]
After updating Contao from 4.5.12 to 4.6.0, the FE stops working with error message:
`The service "wr.onepage.hooks" was not found or is not public.
`
Fortunately a hint to the solution is also included in the same message ...
`See https://symfony.com/doc/current/service_container.html#public-versus-private-services`

After updating " ... src/Resources/config/services.yml, i.e. explicitly defining the hooks to be public:true, the problem is solved.

```
services:
    wr.onepage.hooks:
        class: Wr\OnepageBundle\Service\OnepageHooks
         # explicitly configure the service
        public: true
```
